import React, { useEffect } from "react";
import Head from "next/head";

// Core CSS required for Ionic components to work properly
import "@ionic/core/css/core.css";

// Basic CSS for apps built with Ionic
import "@ionic/core/css/normalize.css";
import "@ionic/core/css/structure.css";
import "@ionic/core/css/typography.css";

// Optional CSS utils that can be commented out
import "tailwindcss/tailwind.css";
import "@ionic/core/css/padding.css";
import "@ionic/core/css/float-elements.css";
import "@ionic/core/css/text-alignment.css";
import "@ionic/core/css/text-transformation.css";
import "@ionic/core/css/flex-utils.css";
import "@ionic/core/css/display.css";

// custom css
import "@/styles/global.scss";

import Player from "@/components/player";
import Menu from "@/components/ui/Menu";
import { IonApp, IonPage, setupIonicReact, IonContent } from "@ionic/react";
import NonSSRWrapper from "../components/core/NoSSRWrapper";
import { useRouter } from "next/router";
import { setIsBack } from "@/store/local";

function MyApp({ Component, pageProps }) {
	setupIonicReact();

	const router = useRouter();
	useEffect(() => {
		router.beforePopState(() => {
			setIsBack(true);
			return true;
		});
	}, [router]);

	// return (
	//   <>
	//     <Head>
	//       <meta
	//         name="viewport"
	//         content="width=device-width, initial-scale=1.0, viewport-fit=cover"
	//       ></meta>
	//     </Head>
	//     <Component {...pageProps} />
	//     {/* <Script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></Script> */}
	//   </>
	// );

	return (
		<>
			<NonSSRWrapper>
				<Menu />
				<Player />
			</NonSSRWrapper>

			<IonApp>
				<IonPage className="page-primary" id="main-content">
					<Head>
						<title>Create Next App</title>
						<meta name="description" content="Generated by create next app" />
						<meta
							name="viewport"
							content="width=device-width, initial-scale=1, viewport-fit=cover"
						/>
						<link rel="icon" href="/favicon.ico" />
					</Head>
					<NonSSRWrapper>
						<Component {...pageProps} />
					</NonSSRWrapper>
				</IonPage>
			</IonApp>
		</>
	);
}

export default MyApp;
