import React from "react";
import styled from "@emotion/styled";
/**
 * `<AudioPlayer>` ('Audio Player')
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <AudioPlayer/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c0847661-6607-41c8-afb3-4b4f3687a3d6)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : unknown://undefined/1:423 -->
 */
export default function AudioPlayer() {
  return (
    <RootWrapperAudioPlayer>
      <StatusBar>
        <Battery>
          <Border />
          <Cap xmlns="http://www.w3.org/2000/svg">
            <path
              fill="rgb(59, 79, 125)"
              d="M0 0L0 4C0.804731 3.66122 1.32804 2.87313 1.32804 2C1.32804 1.12687 0.804731 0.338777 0 0"
            />
          </Cap>
          <Capacity />
        </Battery>
        <Wifi
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9e807696-8f76-4ede-9b54-b3c778d58d81"
          alt="image of Wifi"
        />
        <CellularConnection
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9814162f-894a-4d68-8885-62b06a210347"
          alt="image of CellularConnection"
        />
        <TimeStyle>
          <Time>9:41</Time>
        </TimeStyle>
      </StatusBar>
      <Vector xmlns="http://www.w3.org/2000/svg">
        <path
          fill="rgb(61, 61, 63)"
          d="M12.375 0L1.125 0C0.50625 0 0 0.50625 0 1.125C0 1.74375 0.50625 2.25 1.125 2.25L12.375 2.25C12.9937 2.25 13.5 1.74375 13.5 1.125C13.5 0.50625 12.9937 0 12.375 0ZM12.375 4.5L1.125 4.5C0.50625 4.5 0 5.00625 0 5.625C0 6.24375 0.50625 6.75 1.125 6.75L12.375 6.75C12.9937 6.75 13.5 6.24375 13.5 5.625C13.5 5.00625 12.9937 4.5 12.375 4.5ZM1.125 11.25L7.875 11.25C8.49375 11.25 9 10.7437 9 10.125C9 9.50625 8.49375 9 7.875 9L1.125 9C0.50625 9 0 9.50625 0 10.125C0 10.7437 0.50625 11.25 1.125 11.25ZM18 0C16.7625 0 15.75 1.0125 15.75 2.25L15.75 9.2025C15.4012 9.07875 15.0188 9 14.625 9C12.555 9 10.935 10.845 11.3063 12.9825C11.5425 14.3438 12.6562 15.4575 14.0175 15.6938C16.155 16.065 18 14.445 18 12.375L18 2.25L20.25 2.25C20.8687 2.25 21.375 1.74375 21.375 1.125C21.375 0.50625 20.8687 0 20.25 0L18 0Z"
        />
      </Vector>
      <Group59>
        <Group20>
          <Ellipse1 />
          <Ellipse2 />
          <Ellipse3 />
          <Subtract
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/f334a4bb-a4e3-4e4e-bc6a-8047d4fc74bd"
            alt="image of Subtract"
          />
        </Group20>
        <Ellipse22 />
        <Group2>
          <Line1 />
          <Line16 />
          <Line4 />
          <Line8 />
          <Line2 />
          <Line5 />
          <Line3 />
        </Group2>
      </Group59>
      <Group82>
        <IcOutlineIosShare
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/d7f38a6e-1875-41b2-a43b-7678167e2b60"
          alt="icon"
        />
        <IcRoundStarBorder
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/7900a437-f278-4673-8610-c8f0027eff46"
          alt="icon"
        />
        <MaterialSymbolsHistoryRounded
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/523aed0b-cc68-4940-8b89-1d0a197fae3e"
          alt="icon"
        />
      </Group82>
      <Group85>
        <Group71>
          <Group28>
            <Ellipse219 />
          </Group28>
          <Group31>
            <Polygon1 xmlns="http://www.w3.org/2000/svg">
              <path
                fill="transparent"
                d="M4.40206 1.5C4.78696 0.833335 5.74921 0.833333 6.13411 1.5L8.96435 6.40212C9.34925 7.06879 8.86812 7.90212 8.09832 7.90212L2.43784 7.90212C1.66804 7.90212 1.18691 7.06879 1.57181 6.40212L4.40206 1.5Z"
              />
            </Polygon1>
            <Polygon2 xmlns="http://www.w3.org/2000/svg">
              <path
                fill="transparent"
                d="M4.40206 1.5C4.78696 0.833335 5.74921 0.833333 6.13411 1.5L8.96435 6.40212C9.34925 7.06879 8.86812 7.90212 8.09832 7.90212L2.43784 7.90212C1.66804 7.90212 1.18691 7.06879 1.57181 6.40212L4.40206 1.5Z"
              />
            </Polygon2>
          </Group31>
        </Group71>
        <Group70>
          <Group28>
            <Ellipse219 />
          </Group28>
          <Group41>
            <Polygon1_0001 xmlns="http://www.w3.org/2000/svg">
              <path
                fill="transparent"
                d="M4.40206 1.5C4.78696 0.833335 5.74921 0.833333 6.13411 1.5L8.96435 6.40212C9.34925 7.06879 8.86812 7.90212 8.09832 7.90212L2.43784 7.90212C1.66804 7.90212 1.18691 7.06879 1.57181 6.40212L4.40206 1.5Z"
              />
            </Polygon1_0001>
            <Polygon2 xmlns="http://www.w3.org/2000/svg">
              <path
                fill="transparent"
                d="M4.40206 1.5C4.78696 0.833335 5.74921 0.833333 6.13411 1.5L8.96435 6.40212C9.34925 7.06879 8.86812 7.90212 8.09832 7.90212L2.43784 7.90212C1.66804 7.90212 1.18691 7.06879 1.57181 6.40212L4.40206 1.5Z"
              />
            </Polygon2>
          </Group41>
        </Group70>
        <Group72>
          <Group39>
            <Ellipse228 />
          </Group39>
          <Group42>
            <Rectangle5 />
            <Rectangle6 />
          </Group42>
        </Group72>
        <IcRoundRepeatOne
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/0e9d8a21-71e5-464c-9931-5f2c8ba62f63"
          alt="icon"
        />
        <PhShuffleAngularBold
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/d4e50a1e-8c71-4a79-be02-43a7f419c6fc"
          alt="icon"
        />
      </Group85>
      <Timeline>
        <Ellipse9 />
        <Rectangle3 />
        <Rectangle4 />
        <Ellipse8 />
        <_105>1:05</_105>
        <_310>3:10</_310>
      </Timeline>
      <Group84>
        <QuranRadioFinal1
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1ae32ed3-18a0-41c3-a61a-42b5dc4d72f4"
          alt="image of QuranRadioFinal1"
        />
        <Vector_0001
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/f743d91d-c309-4ff0-8469-8523f8797a31"
          alt="image of Vector"
        />
        <Subtract_0001
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/540a357f-e0a6-4098-88eb-70f873cb8c0b"
          alt="image of Subtract"
        />
      </Group84>
      <Group55>
        <Group13>
          <ReciterMisharyRashidAlafasy>
            Reciter - Mishary Rashid Alafasy
          </ReciterMisharyRashidAlafasy>
        </Group13>
        <Group21>
          <AlQadrTheNightOfDecree>
            Al-Qadr (The Night of Decree)
          </AlQadrTheNightOfDecree>
        </Group21>
      </Group55>
      <HomeIndicator />
    </RootWrapperAudioPlayer>
  );
}

const RootWrapperAudioPlayer = styled.div`
  min-height: 100vh;
  background: linear-gradient(90deg, rgb(206, 223, 229), rgb(121, 123, 136));
  border-radius: 30px;
  position: relative;
`;

const StatusBar = styled.div`
  width: 389px;
  height: 45px;
  position: absolute;
  left: 13px;
  top: 0px;
`;

const Battery = styled.div`
  width: 24px;
  height: 11px;
  position: absolute;
  left: 350px;
  top: 17px;
`;

const Border = styled.div`
  width: 22px;
  height: 11px;
  border: solid 1px rgb(59, 79, 125);
  border-radius: 3px;
  position: absolute;
  top: 0px;
  right: 2px;
  opacity: 0.3;
`;

const Cap = styled.svg`
  width: 1px;
  height: 4px;
  position: absolute;
  top: 4px;
  right: -0px;
  opacity: 0.4;
`;

const Capacity = styled.div`
  width: 18px;
  height: 7px;
  background-color: rgb(61, 61, 63);
  border-radius: 1px;
  position: absolute;
  top: 2px;
  right: 4px;
`;

const Wifi = styled.img`
  width: 15px;
  height: 11px;
  object-fit: cover;
  position: absolute;
  top: 17px;
  right: 44px;
`;

const CellularConnection = styled.img`
  width: 17px;
  height: 11px;
  object-fit: cover;
  position: absolute;
  top: 18px;
  right: 64px;
`;

const TimeStyle = styled.div`
  width: 54px;
  height: 21px;
  position: absolute;
  left: 21px;
  top: 11px;
`;

const Time = styled.span`
  color: rgb(61, 61, 63);
  text-overflow: ellipsis;
  font-size: 15px;
  font-family: "SF Pro Display", sans-serif;
  font-weight: 500;
  text-align: center;
  width: 54px;
  position: absolute;
  left: 0px;
  top: calc((calc((50% + 2px)) - 9px));
`;

const Vector = styled.svg`
  width: 21px;
  height: 16px;
  position: absolute;
  left: 326px;
  top: 409px;
  right: 67px;
  bottom: 471px;
`;

const Group59 = styled.div`
  width: 159px;
  height: 159px;
  position: absolute;
  left: 128px;
  top: 336px;
`;

const Group20 = styled.div`
  width: 159px;
  height: 159px;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const Ellipse1 = styled.div`
  width: 159px;
  height: 159px;
  box-shadow: 3px 7px 4px rgba(0, 0, 0, 0.3),
    -6px -5px 7px -1px rgba(86, 100, 103, 0.94);
  background-color: rgb(27, 27, 27);
  border-radius: 159px / 159px;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const Ellipse2 = styled.div`
  width: 153px;
  height: 153px;
  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
  border-radius: 153px / 153px;
  position: absolute;
  left: 3px;
  top: 3px;
`;

const Ellipse3 = styled.div`
  width: 159px;
  height: 159px;
  border-radius: 159px / 159px;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const Subtract = styled.img`
  width: 80px;
  height: 80px;
  object-fit: cover;
  position: absolute;
  left: 79px;
  top: 0px;
`;

const Ellipse22 = styled.div`
  width: 153px;
  height: 153px;
  box-shadow: -2px -2px 5px rgba(0, 0, 0, 0.5), 2px 2px 5px rgba(0, 0, 0, 0.5);
  background-color: rgba(144, 145, 152, 0.22);
  border-radius: 153px / 153px;
  position: absolute;
  left: 3px;
  top: 3px;
  backdrop-filter: blur(6px);
`;

const Group2 = styled.div`
  width: 33px;
  height: 25px;
  position: absolute;
  left: 63px;
  top: 68px;
`;

const Line1 = styled.div`
  width: 21px;
  height: 0px;
  border-top: solid 2px rgb(27, 165, 132);
  position: absolute;
  left: 11px;
  top: 4px;
  transform: rotate(-270deg);
  transform-origin: top left;
`;

const Line16 = styled.div`
  width: 17px;
  height: 0px;
  border-top: solid 2px rgb(27, 165, 132);
  position: absolute;
  left: 33px;
  top: 3px;
  transform: rotate(-270deg);
  transform-origin: top left;
`;

const Line4 = styled.div`
  width: 17px;
  height: 0px;
  border-top: solid 2px rgb(27, 165, 132);
  position: absolute;
  left: 22px;
  top: 0px;
  transform: rotate(-270deg);
  transform-origin: top left;
`;

const Line8 = styled.div`
  width: 17px;
  height: 0px;
  border-top: solid 2px rgb(27, 165, 132);
  position: absolute;
  left: 0px;
  top: 4px;
  transform: rotate(-270deg);
  transform-origin: top left;
`;

const Line2 = styled.div`
  width: 7px;
  height: 0px;
  border-top: solid 2px rgb(27, 165, 132);
  position: absolute;
  left: 6px;
  top: 13px;
  transform: rotate(-270deg);
  transform-origin: top left;
`;

const Line5 = styled.div`
  width: 10px;
  height: 0px;
  border-top: solid 2px rgb(27, 165, 132);
  position: absolute;
  left: 27px;
  top: 13px;
  transform: rotate(-270deg);
  transform-origin: top left;
`;

const Line3 = styled.div`
  width: 8px;
  height: 0px;
  border-top: solid 2px rgb(27, 165, 132);
  position: absolute;
  left: 16px;
  top: 8px;
  transform: rotate(-270deg);
  transform-origin: top left;
`;

const Group82 = styled.div`
  width: 268px;
  height: 29px;
  position: absolute;
  left: 73px;
  top: 520px;
`;

const IcOutlineIosShare = styled.img`
  width: 25px;
  height: 25px;
  object-fit: cover;
  position: absolute;
  left: 123px;
  top: 0px;
`;

const IcRoundStarBorder = styled.img`
  width: 28px;
  height: 28px;
  object-fit: cover;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const MaterialSymbolsHistoryRounded = styled.img`
  width: 25px;
  height: 25px;
  object-fit: cover;
  position: absolute;
  left: 243px;
  top: 4px;
`;

const Group85 = styled.div`
  width: 338px;
  height: 57px;
  position: absolute;
  left: 38px;
  top: 724px;
`;

const Group71 = styled.div`
  width: 41px;
  height: 41px;
  position: absolute;
  left: 236px;
  top: 9px;
`;

const Group28 = styled.div`
  width: 41px;
  height: 41px;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const Ellipse219 = styled.div`
  width: 41px;
  height: 41px;
  background-color: rgb(88, 88, 94);
  border-radius: 41px / 41px;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const Group31 = styled.div`
  width: 17px;
  height: 11px;
  position: absolute;
  left: 29px;
  top: 15px;
  transform: rotate(-180deg);
  transform-origin: top left;
`;

const Polygon1 = styled.svg`
  width: 11px;
  height: 11px;
  position: absolute;
  left: 0px;
  top: 11px;
  transform: rotate(-90deg);
  transform-origin: top left;
`;

const Polygon2 = styled.svg`
  width: 11px;
  height: 11px;
  position: absolute;
  left: 6px;
  top: 11px;
  transform: rotate(-90deg);
  transform-origin: top left;
`;

const Group70 = styled.div`
  width: 41px;
  height: 41px;
  position: absolute;
  left: 63px;
  top: 9px;
`;

const Group41 = styled.div`
  width: 17px;
  height: 11px;
  position: absolute;
  left: 12px;
  top: 15px;
`;

const Polygon1_0001 = styled.svg`
  width: 11px;
  height: 11px;
  position: absolute;
  left: -0px;
  top: 11px;
  transform: rotate(-90deg);
  transform-origin: top left;
`;

const Group72 = styled.div`
  width: 57px;
  height: 57px;
  position: absolute;
  left: 141px;
  top: 0px;
`;

const Group39 = styled.div`
  width: 57px;
  height: 57px;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const Ellipse228 = styled.div`
  width: 57px;
  height: 57px;
  background: linear-gradient(-225deg, rgb(61, 61, 63), rgba(61, 61, 63, 0.74));
  border-radius: 57px / 57px;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const Group42 = styled.div`
  width: 8px;
  height: 15px;
  position: absolute;
  left: 24px;
  top: 21px;
`;

const Rectangle5 = styled.div`
  width: 3px;
  height: 15px;
  background-color: white;
  border-radius: 1px;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const Rectangle6 = styled.div`
  width: 3px;
  height: 15px;
  background-color: white;
  border-radius: 1px;
  position: absolute;
  left: 5px;
  top: -0px;
`;

const IcRoundRepeatOne = styled.img`
  width: 25px;
  height: 25px;
  object-fit: cover;
  position: absolute;
  left: 0px;
  top: 16px;
`;

const PhShuffleAngularBold = styled.img`
  width: 24px;
  height: 24px;
  object-fit: cover;
  position: absolute;
  left: 314px;
  top: 17px;
`;

const Timeline = styled.div`
  width: 332px;
  height: 17px;
  position: absolute;
  left: 41px;
  top: 640px;
`;

const Ellipse9 = styled.div`
  width: 17px;
  height: 17px;
  background-color: rgba(217, 217, 217, 0.25);
  border-radius: 17px / 17px;
  position: absolute;
  left: calc((calc((50% + -38px)) - 9px));
  top: calc((calc((50% + 0px)) - 9px));
`;

const Rectangle3 = styled.div`
  width: 282px;
  height: 5px;
  background-color: rgb(217, 217, 217);
  border-radius: 8px;
  position: absolute;
  left: 25px;
  top: 6px;
`;

const Rectangle4 = styled.div`
  width: 104px;
  height: 5px;
  background: linear-gradient(
    -90deg,
    rgb(30, 153, 125),
    rgb(87, 194, 173),
    rgba(87, 194, 173, 0.6)
  );
  border-radius: 8px;
  position: absolute;
  left: 25px;
  top: 6px;
`;

const Ellipse8 = styled.div`
  width: 7px;
  height: 7px;
  background-color: rgb(31, 154, 126);
  border-radius: 7px / 7px;
  position: absolute;
  left: 125px;
  top: 5px;
`;

const _105 = styled.span`
  color: rgb(61, 61, 63);
  text-overflow: ellipsis;
  font-size: 11px;
  font-family: "SF Pro Display", sans-serif;
  font-weight: 400;
  text-align: center;
  position: absolute;
  left: 0px;
  top: 2px;
`;

const _310 = styled.span`
  color: rgb(61, 61, 63);
  text-overflow: ellipsis;
  font-size: 11px;
  font-family: "SF Pro Display", sans-serif;
  font-weight: 400;
  text-align: center;
  position: absolute;
  left: 312px;
  top: 2px;
`;

const Group84 = styled.div`
  width: 335px;
  height: 75px;
  position: absolute;
  left: 41px;
  top: 70px;
`;

const QuranRadioFinal1 = styled.img`
  width: 133px;
  height: 75px;
  object-fit: cover;
  position: absolute;
  left: 100px;
  top: 0px;
`;

const Vector_0001 = styled.img`
  object-fit: cover;
  position: absolute;
  left: 0px;
  top: 35px;
  right: 317px;
  bottom: 30px;
`;

const Subtract_0001 = styled.img`
  width: 22px;
  height: 22px;
  object-fit: cover;
  position: absolute;
  left: 313px;
  top: 32px;
`;

const Group55 = styled.div`
  width: 223px;
  height: 42px;
  position: absolute;
  left: 95px;
  top: 216px;
`;

const Group13 = styled.div`
  width: 223px;
  height: 19px;
  position: absolute;
  box-shadow: 0px 0px 1px rgba(0, 0, 0, 0.99);
  left: 0px;
  top: 0px;
`;

const ReciterMisharyRashidAlafasy = styled.span`
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: "SF Pro Display", sans-serif;
  font-weight: 500;
  text-align: left;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const Group21 = styled.div`
  width: 152px;
  height: 14px;
  position: absolute;
  left: 36px;
  top: 28px;
`;

const AlQadrTheNightOfDecree = styled.span`
  color: rgb(61, 61, 63);
  text-overflow: ellipsis;
  font-size: 12px;
  font-family: "SF Pro Display", sans-serif;
  font-weight: 400;
  text-align: left;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const HomeIndicator = styled.div`
  width: 134px;
  height: 5px;
  background-color: rgb(88, 88, 93);
  border-radius: 100px;
  position: absolute;
  left: calc((calc((50% + 0px)) - 67px));
  bottom: 6px;
  backdrop-filter: blur(40px);
`;
